#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomGroupApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Allwell")]
	public partial class AllwellDataAccessDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertResult(Result instance);
    partial void UpdateResult(Result instance);
    partial void DeleteResult(Result instance);
    partial void InsertTest(Test instance);
    partial void UpdateTest(Test instance);
    partial void DeleteTest(Test instance);
    partial void InsertStudentLanguagePref(StudentLanguagePref instance);
    partial void UpdateStudentLanguagePref(StudentLanguagePref instance);
    partial void DeleteStudentLanguagePref(StudentLanguagePref instance);
    #endregion
		
		public AllwellDataAccessDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AllwellConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AllwellDataAccessDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AllwellDataAccessDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AllwellDataAccessDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AllwellDataAccessDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Result> Results
		{
			get
			{
				return this.GetTable<Result>();
			}
		}
		
		public System.Data.Linq.Table<Test> Tests
		{
			get
			{
				return this.GetTable<Test>();
			}
		}
		
		public System.Data.Linq.Table<StudentLanguagePref> StudentLanguagePrefs
		{
			get
			{
				return this.GetTable<StudentLanguagePref>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Results")]
	public partial class Result : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Testnum;
		
		private string _Name;
		
		private System.DateTime _Dob;
		
		private System.Nullable<char> _Sex;
		
		private System.Nullable<char> _Speak;
		
		private System.Nullable<char> _Live_in_as;
		
		private System.Nullable<int> _Sem;
		
		private System.Nullable<int> _Form;
		
		private System.Nullable<char> _Level;
		
		private System.Nullable<bool> _Retst;
		
		private System.Nullable<int> _Genab;
		
		private System.Nullable<int> _Genab2;
		
		private System.Nullable<int> _Mathab;
		
		private System.Nullable<int> _Mathper;
		
		private System.Nullable<int> _Reading;
		
		private System.Nullable<int> _Spelling;
		
		private System.Nullable<int> _Written;
		
		private System.Nullable<int> _Verbal;
		
		private System.Nullable<int> _Nonverbal;
		
		private string _Mathcor;
		
		private string _Sum_code;
		
		private System.Nullable<int> _Vc;
		
		private System.Nullable<int> _Vr;
		
		private System.Nullable<int> _Fr;
		
		private System.Nullable<int> _Qr;
		
		private System.Nullable<decimal> _Ca;
		
		private System.Nullable<int> _Iq1;
		
		private System.Nullable<int> _Iq2;
		
		private System.Nullable<int> _Iqs;
		
		private System.Nullable<int> _Iq12;
		
		private System.Nullable<int> _Iq22;
		
		private System.Nullable<int> _Iqs2;
		
		private System.Nullable<int> _Vil;
		
		private System.Nullable<int> _Vih;
		
		private System.Nullable<int> _Vis;
		
		private System.Nullable<int> _Nvil;
		
		private System.Nullable<int> _Nvih;
		
		private System.Nullable<int> _Nvis;
		
		private System.Nullable<int> _Mrs;
		
		private System.Nullable<int> _Mst;
		
		private System.Nullable<int> _Prs;
		
		private System.Nullable<int> _Pst;
		
		private System.Nullable<int> _Rrs;
		
		private System.Nullable<int> _Rst;
		
		private System.Nullable<int> _Ri1;
		
		private System.Nullable<int> _Ri2;
		
		private System.Nullable<int> _Srs;
		
		private System.Nullable<int> _Sst;
		
		private System.Nullable<int> _We;
		
		private System.Nullable<decimal> _Wr;
		
		private string _Group;
		
		private System.Nullable<int> _Math;
		
		private string _Lan_bas_sb;
		
		private string _Sum_code_r;
		
		private string _Sum_code_a;
		
		private string _Sum_code_s;
		
		private string _Sum_code_i;
		
		private string _Sum_code_c;
		
		private string _Sum_code_e;
		
		private System.Nullable<int> _Char_wrk_m;
		
		private System.Nullable<int> _Char_wrk_s;
		
		private System.Nullable<int> _Char_wrk_d;
		
		private System.Nullable<int> _Car_aware;
		
		private string _Choice1;
		
		private string _Choice2;
		
		private string _Choice3;
		
		private string _Student_id;
		
		private string _Csv_genab;
		
		private string _Csv_read;
		
		private string _Csv_math;
		
		private string _Csv_spell;
		
		private System.Nullable<decimal> _S_genab;
		
		private System.Nullable<decimal> _S_verbal;
		
		private System.Nullable<decimal> _S_nonverb;
		
		private System.Nullable<decimal> _S_mathper;
		
		private System.Nullable<decimal> _S_reading;
		
		private System.Nullable<decimal> _S_written;
		
		private System.Nullable<decimal> _S_spelling;
		
		private System.Nullable<bool> _Fkg;
		
		private string _Edu_plan;
		
		private string _Custom1;
		
		private string _IntStudent;
		
		private string _Form_mod;
		
		private System.Nullable<int> _NewWr;
		
		private System.Nullable<int> _Wrt;
		
		private string _csv_writing;
		
		private System.Nullable<int> _t_genab;
		
		private System.Nullable<int> _t_verbal;
		
		private System.Nullable<int> _t_nverbal;
		
		private System.Nullable<int> _t_pst;
		
		private System.Nullable<int> _t_rst;
		
		private System.Nullable<int> _t_sst;
		
		private System.Nullable<int> _t_wr;
		
		private System.Nullable<int> _t_mst;
		
		private System.Nullable<int> _Serialno;
		
		private string _Wr_task;
		
		private System.Nullable<short> _Wr_genre;
		
		private System.Nullable<short> _Wr_args;
		
		private System.Nullable<short> _Wr_rhtdev;
		
		private System.Nullable<short> _Wr_nardev;
		
		private System.Nullable<short> _Wr_thmdev;
		
		private System.Nullable<short> _Wr_vocab;
		
		private System.Nullable<short> _Wr_senstr;
		
		private System.Nullable<short> _Wr_synten;
		
		private System.Nullable<short> _Wr_punct;
		
		private System.Nullable<short> _Wr_spell;
		
		private System.Nullable<short> _Wr_level;
		
		private System.Nullable<short> _Wr_sem;
		
		private System.Nullable<int> _Char_wrk_i;
		
		private string _Genabcor;
		
		private string _Spellcor;
		
		private string _Readcor;
		
		private System.Nullable<int> _GlobalStudentId;
		
		private string _SchoolPref1;
		
		private string _SchoolPref2;
		
		private string _SchoolPref3;
		
		private string _SchoolPref4;
		
		private string _SchoolPref5;
		
		private System.Nullable<int> _ScholarshipApplicantId;
		
		private System.Nullable<short> _Npi_Read;
		
		private System.Nullable<short> _Npi_Math;
		
		private System.Nullable<short> _Npi_Writing;
		
		private string _Notes;
		
		private System.Nullable<System.DateTime> _Published;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTestnumChanging(int value);
    partial void OnTestnumChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDobChanging(System.DateTime value);
    partial void OnDobChanged();
    partial void OnSexChanging(System.Nullable<char> value);
    partial void OnSexChanged();
    partial void OnSpeakChanging(System.Nullable<char> value);
    partial void OnSpeakChanged();
    partial void OnLive_in_asChanging(System.Nullable<char> value);
    partial void OnLive_in_asChanged();
    partial void OnSemChanging(System.Nullable<int> value);
    partial void OnSemChanged();
    partial void OnFormChanging(System.Nullable<int> value);
    partial void OnFormChanged();
    partial void OnLevelChanging(System.Nullable<char> value);
    partial void OnLevelChanged();
    partial void OnRetstChanging(System.Nullable<bool> value);
    partial void OnRetstChanged();
    partial void OnGenabChanging(System.Nullable<int> value);
    partial void OnGenabChanged();
    partial void OnGenab2Changing(System.Nullable<int> value);
    partial void OnGenab2Changed();
    partial void OnMathabChanging(System.Nullable<int> value);
    partial void OnMathabChanged();
    partial void OnMathperChanging(System.Nullable<int> value);
    partial void OnMathperChanged();
    partial void OnReadingChanging(System.Nullable<int> value);
    partial void OnReadingChanged();
    partial void OnSpellingChanging(System.Nullable<int> value);
    partial void OnSpellingChanged();
    partial void OnWrittenChanging(System.Nullable<int> value);
    partial void OnWrittenChanged();
    partial void OnVerbalChanging(System.Nullable<int> value);
    partial void OnVerbalChanged();
    partial void OnNonverbalChanging(System.Nullable<int> value);
    partial void OnNonverbalChanged();
    partial void OnMathcorChanging(string value);
    partial void OnMathcorChanged();
    partial void OnSum_codeChanging(string value);
    partial void OnSum_codeChanged();
    partial void OnVcChanging(System.Nullable<int> value);
    partial void OnVcChanged();
    partial void OnVrChanging(System.Nullable<int> value);
    partial void OnVrChanged();
    partial void OnFrChanging(System.Nullable<int> value);
    partial void OnFrChanged();
    partial void OnQrChanging(System.Nullable<int> value);
    partial void OnQrChanged();
    partial void OnCaChanging(System.Nullable<decimal> value);
    partial void OnCaChanged();
    partial void OnIq1Changing(System.Nullable<int> value);
    partial void OnIq1Changed();
    partial void OnIq2Changing(System.Nullable<int> value);
    partial void OnIq2Changed();
    partial void OnIqsChanging(System.Nullable<int> value);
    partial void OnIqsChanged();
    partial void OnIq12Changing(System.Nullable<int> value);
    partial void OnIq12Changed();
    partial void OnIq22Changing(System.Nullable<int> value);
    partial void OnIq22Changed();
    partial void OnIqs2Changing(System.Nullable<int> value);
    partial void OnIqs2Changed();
    partial void OnVilChanging(System.Nullable<int> value);
    partial void OnVilChanged();
    partial void OnVihChanging(System.Nullable<int> value);
    partial void OnVihChanged();
    partial void OnVisChanging(System.Nullable<int> value);
    partial void OnVisChanged();
    partial void OnNvilChanging(System.Nullable<int> value);
    partial void OnNvilChanged();
    partial void OnNvihChanging(System.Nullable<int> value);
    partial void OnNvihChanged();
    partial void OnNvisChanging(System.Nullable<int> value);
    partial void OnNvisChanged();
    partial void OnMrsChanging(System.Nullable<int> value);
    partial void OnMrsChanged();
    partial void OnMstChanging(System.Nullable<int> value);
    partial void OnMstChanged();
    partial void OnPrsChanging(System.Nullable<int> value);
    partial void OnPrsChanged();
    partial void OnPstChanging(System.Nullable<int> value);
    partial void OnPstChanged();
    partial void OnRrsChanging(System.Nullable<int> value);
    partial void OnRrsChanged();
    partial void OnRstChanging(System.Nullable<int> value);
    partial void OnRstChanged();
    partial void OnRi1Changing(System.Nullable<int> value);
    partial void OnRi1Changed();
    partial void OnRi2Changing(System.Nullable<int> value);
    partial void OnRi2Changed();
    partial void OnSrsChanging(System.Nullable<int> value);
    partial void OnSrsChanged();
    partial void OnSstChanging(System.Nullable<int> value);
    partial void OnSstChanged();
    partial void OnWeChanging(System.Nullable<int> value);
    partial void OnWeChanged();
    partial void OnWrChanging(System.Nullable<decimal> value);
    partial void OnWrChanged();
    partial void OnGroupChanging(string value);
    partial void OnGroupChanged();
    partial void OnMathChanging(System.Nullable<int> value);
    partial void OnMathChanged();
    partial void OnLan_bas_sbChanging(string value);
    partial void OnLan_bas_sbChanged();
    partial void OnSum_code_rChanging(string value);
    partial void OnSum_code_rChanged();
    partial void OnSum_code_aChanging(string value);
    partial void OnSum_code_aChanged();
    partial void OnSum_code_sChanging(string value);
    partial void OnSum_code_sChanged();
    partial void OnSum_code_iChanging(string value);
    partial void OnSum_code_iChanged();
    partial void OnSum_code_cChanging(string value);
    partial void OnSum_code_cChanged();
    partial void OnSum_code_eChanging(string value);
    partial void OnSum_code_eChanged();
    partial void OnChar_wrk_mChanging(System.Nullable<int> value);
    partial void OnChar_wrk_mChanged();
    partial void OnChar_wrk_sChanging(System.Nullable<int> value);
    partial void OnChar_wrk_sChanged();
    partial void OnChar_wrk_dChanging(System.Nullable<int> value);
    partial void OnChar_wrk_dChanged();
    partial void OnCar_awareChanging(System.Nullable<int> value);
    partial void OnCar_awareChanged();
    partial void OnChoice1Changing(string value);
    partial void OnChoice1Changed();
    partial void OnChoice2Changing(string value);
    partial void OnChoice2Changed();
    partial void OnChoice3Changing(string value);
    partial void OnChoice3Changed();
    partial void OnStudent_idChanging(string value);
    partial void OnStudent_idChanged();
    partial void OnCsv_genabChanging(string value);
    partial void OnCsv_genabChanged();
    partial void OnCsv_readChanging(string value);
    partial void OnCsv_readChanged();
    partial void OnCsv_mathChanging(string value);
    partial void OnCsv_mathChanged();
    partial void OnCsv_spellChanging(string value);
    partial void OnCsv_spellChanged();
    partial void OnS_genabChanging(System.Nullable<decimal> value);
    partial void OnS_genabChanged();
    partial void OnS_verbalChanging(System.Nullable<decimal> value);
    partial void OnS_verbalChanged();
    partial void OnS_nonverbChanging(System.Nullable<decimal> value);
    partial void OnS_nonverbChanged();
    partial void OnS_mathperChanging(System.Nullable<decimal> value);
    partial void OnS_mathperChanged();
    partial void OnS_readingChanging(System.Nullable<decimal> value);
    partial void OnS_readingChanged();
    partial void OnS_writtenChanging(System.Nullable<decimal> value);
    partial void OnS_writtenChanged();
    partial void OnS_spellingChanging(System.Nullable<decimal> value);
    partial void OnS_spellingChanged();
    partial void OnFkgChanging(System.Nullable<bool> value);
    partial void OnFkgChanged();
    partial void OnEdu_planChanging(string value);
    partial void OnEdu_planChanged();
    partial void OnCustom1Changing(string value);
    partial void OnCustom1Changed();
    partial void OnIntStudentChanging(string value);
    partial void OnIntStudentChanged();
    partial void OnForm_modChanging(string value);
    partial void OnForm_modChanged();
    partial void OnNewWrChanging(System.Nullable<int> value);
    partial void OnNewWrChanged();
    partial void OnWrtChanging(System.Nullable<int> value);
    partial void OnWrtChanged();
    partial void Oncsv_writingChanging(string value);
    partial void Oncsv_writingChanged();
    partial void Ont_genabChanging(System.Nullable<int> value);
    partial void Ont_genabChanged();
    partial void Ont_verbalChanging(System.Nullable<int> value);
    partial void Ont_verbalChanged();
    partial void Ont_nverbalChanging(System.Nullable<int> value);
    partial void Ont_nverbalChanged();
    partial void Ont_pstChanging(System.Nullable<int> value);
    partial void Ont_pstChanged();
    partial void Ont_rstChanging(System.Nullable<int> value);
    partial void Ont_rstChanged();
    partial void Ont_sstChanging(System.Nullable<int> value);
    partial void Ont_sstChanged();
    partial void Ont_wrChanging(System.Nullable<int> value);
    partial void Ont_wrChanged();
    partial void Ont_mstChanging(System.Nullable<int> value);
    partial void Ont_mstChanged();
    partial void OnSerialnoChanging(System.Nullable<int> value);
    partial void OnSerialnoChanged();
    partial void OnWr_taskChanging(string value);
    partial void OnWr_taskChanged();
    partial void OnWr_genreChanging(System.Nullable<short> value);
    partial void OnWr_genreChanged();
    partial void OnWr_argsChanging(System.Nullable<short> value);
    partial void OnWr_argsChanged();
    partial void OnWr_rhtdevChanging(System.Nullable<short> value);
    partial void OnWr_rhtdevChanged();
    partial void OnWr_nardevChanging(System.Nullable<short> value);
    partial void OnWr_nardevChanged();
    partial void OnWr_thmdevChanging(System.Nullable<short> value);
    partial void OnWr_thmdevChanged();
    partial void OnWr_vocabChanging(System.Nullable<short> value);
    partial void OnWr_vocabChanged();
    partial void OnWr_senstrChanging(System.Nullable<short> value);
    partial void OnWr_senstrChanged();
    partial void OnWr_syntenChanging(System.Nullable<short> value);
    partial void OnWr_syntenChanged();
    partial void OnWr_punctChanging(System.Nullable<short> value);
    partial void OnWr_punctChanged();
    partial void OnWr_spellChanging(System.Nullable<short> value);
    partial void OnWr_spellChanged();
    partial void OnWr_levelChanging(System.Nullable<short> value);
    partial void OnWr_levelChanged();
    partial void OnWr_semChanging(System.Nullable<short> value);
    partial void OnWr_semChanged();
    partial void OnChar_wrk_iChanging(System.Nullable<int> value);
    partial void OnChar_wrk_iChanged();
    partial void OnGenabcorChanging(string value);
    partial void OnGenabcorChanged();
    partial void OnSpellcorChanging(string value);
    partial void OnSpellcorChanged();
    partial void OnReadcorChanging(string value);
    partial void OnReadcorChanged();
    partial void OnGlobalStudentIdChanging(System.Nullable<int> value);
    partial void OnGlobalStudentIdChanged();
    partial void OnSchoolPref1Changing(string value);
    partial void OnSchoolPref1Changed();
    partial void OnSchoolPref2Changing(string value);
    partial void OnSchoolPref2Changed();
    partial void OnSchoolPref3Changing(string value);
    partial void OnSchoolPref3Changed();
    partial void OnSchoolPref4Changing(string value);
    partial void OnSchoolPref4Changed();
    partial void OnSchoolPref5Changing(string value);
    partial void OnSchoolPref5Changed();
    partial void OnScholarshipApplicantIdChanging(System.Nullable<int> value);
    partial void OnScholarshipApplicantIdChanged();
    partial void OnNpi_ReadChanging(System.Nullable<short> value);
    partial void OnNpi_ReadChanged();
    partial void OnNpi_MathChanging(System.Nullable<short> value);
    partial void OnNpi_MathChanged();
    partial void OnNpi_WritingChanging(System.Nullable<short> value);
    partial void OnNpi_WritingChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnPublishedChanging(System.Nullable<System.DateTime> value);
    partial void OnPublishedChanged();
    #endregion
		
		public Result()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Testnum", DbType="Int NOT NULL")]
		public int Testnum
		{
			get
			{
				return this._Testnum;
			}
			set
			{
				if ((this._Testnum != value))
				{
					this.OnTestnumChanging(value);
					this.SendPropertyChanging();
					this._Testnum = value;
					this.SendPropertyChanged("Testnum");
					this.OnTestnumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dob", DbType="DateTime NOT NULL")]
		public System.DateTime Dob
		{
			get
			{
				return this._Dob;
			}
			set
			{
				if ((this._Dob != value))
				{
					this.OnDobChanging(value);
					this.SendPropertyChanging();
					this._Dob = value;
					this.SendPropertyChanged("Dob");
					this.OnDobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NChar(1)")]
		public System.Nullable<char> Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speak", DbType="NChar(1)")]
		public System.Nullable<char> Speak
		{
			get
			{
				return this._Speak;
			}
			set
			{
				if ((this._Speak != value))
				{
					this.OnSpeakChanging(value);
					this.SendPropertyChanging();
					this._Speak = value;
					this.SendPropertyChanged("Speak");
					this.OnSpeakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Live_in_as", DbType="NChar(1)")]
		public System.Nullable<char> Live_in_as
		{
			get
			{
				return this._Live_in_as;
			}
			set
			{
				if ((this._Live_in_as != value))
				{
					this.OnLive_in_asChanging(value);
					this.SendPropertyChanging();
					this._Live_in_as = value;
					this.SendPropertyChanged("Live_in_as");
					this.OnLive_in_asChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sem", DbType="Int")]
		public System.Nullable<int> Sem
		{
			get
			{
				return this._Sem;
			}
			set
			{
				if ((this._Sem != value))
				{
					this.OnSemChanging(value);
					this.SendPropertyChanging();
					this._Sem = value;
					this.SendPropertyChanged("Sem");
					this.OnSemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form", DbType="Int")]
		public System.Nullable<int> Form
		{
			get
			{
				return this._Form;
			}
			set
			{
				if ((this._Form != value))
				{
					this.OnFormChanging(value);
					this.SendPropertyChanging();
					this._Form = value;
					this.SendPropertyChanged("Form");
					this.OnFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="NChar(1)")]
		public System.Nullable<char> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Retst", DbType="Bit")]
		public System.Nullable<bool> Retst
		{
			get
			{
				return this._Retst;
			}
			set
			{
				if ((this._Retst != value))
				{
					this.OnRetstChanging(value);
					this.SendPropertyChanging();
					this._Retst = value;
					this.SendPropertyChanged("Retst");
					this.OnRetstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genab", DbType="Int")]
		public System.Nullable<int> Genab
		{
			get
			{
				return this._Genab;
			}
			set
			{
				if ((this._Genab != value))
				{
					this.OnGenabChanging(value);
					this.SendPropertyChanging();
					this._Genab = value;
					this.SendPropertyChanged("Genab");
					this.OnGenabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genab2", DbType="Int")]
		public System.Nullable<int> Genab2
		{
			get
			{
				return this._Genab2;
			}
			set
			{
				if ((this._Genab2 != value))
				{
					this.OnGenab2Changing(value);
					this.SendPropertyChanging();
					this._Genab2 = value;
					this.SendPropertyChanged("Genab2");
					this.OnGenab2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mathab", DbType="Int")]
		public System.Nullable<int> Mathab
		{
			get
			{
				return this._Mathab;
			}
			set
			{
				if ((this._Mathab != value))
				{
					this.OnMathabChanging(value);
					this.SendPropertyChanging();
					this._Mathab = value;
					this.SendPropertyChanged("Mathab");
					this.OnMathabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mathper", DbType="Int")]
		public System.Nullable<int> Mathper
		{
			get
			{
				return this._Mathper;
			}
			set
			{
				if ((this._Mathper != value))
				{
					this.OnMathperChanging(value);
					this.SendPropertyChanging();
					this._Mathper = value;
					this.SendPropertyChanged("Mathper");
					this.OnMathperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reading", DbType="Int")]
		public System.Nullable<int> Reading
		{
			get
			{
				return this._Reading;
			}
			set
			{
				if ((this._Reading != value))
				{
					this.OnReadingChanging(value);
					this.SendPropertyChanging();
					this._Reading = value;
					this.SendPropertyChanged("Reading");
					this.OnReadingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spelling", DbType="Int")]
		public System.Nullable<int> Spelling
		{
			get
			{
				return this._Spelling;
			}
			set
			{
				if ((this._Spelling != value))
				{
					this.OnSpellingChanging(value);
					this.SendPropertyChanging();
					this._Spelling = value;
					this.SendPropertyChanged("Spelling");
					this.OnSpellingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Written", DbType="Int")]
		public System.Nullable<int> Written
		{
			get
			{
				return this._Written;
			}
			set
			{
				if ((this._Written != value))
				{
					this.OnWrittenChanging(value);
					this.SendPropertyChanging();
					this._Written = value;
					this.SendPropertyChanged("Written");
					this.OnWrittenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verbal", DbType="Int")]
		public System.Nullable<int> Verbal
		{
			get
			{
				return this._Verbal;
			}
			set
			{
				if ((this._Verbal != value))
				{
					this.OnVerbalChanging(value);
					this.SendPropertyChanging();
					this._Verbal = value;
					this.SendPropertyChanged("Verbal");
					this.OnVerbalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nonverbal", DbType="Int")]
		public System.Nullable<int> Nonverbal
		{
			get
			{
				return this._Nonverbal;
			}
			set
			{
				if ((this._Nonverbal != value))
				{
					this.OnNonverbalChanging(value);
					this.SendPropertyChanging();
					this._Nonverbal = value;
					this.SendPropertyChanged("Nonverbal");
					this.OnNonverbalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mathcor", DbType="VarChar(100)")]
		public string Mathcor
		{
			get
			{
				return this._Mathcor;
			}
			set
			{
				if ((this._Mathcor != value))
				{
					this.OnMathcorChanging(value);
					this.SendPropertyChanging();
					this._Mathcor = value;
					this.SendPropertyChanged("Mathcor");
					this.OnMathcorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum_code", DbType="NVarChar(6)")]
		public string Sum_code
		{
			get
			{
				return this._Sum_code;
			}
			set
			{
				if ((this._Sum_code != value))
				{
					this.OnSum_codeChanging(value);
					this.SendPropertyChanging();
					this._Sum_code = value;
					this.SendPropertyChanged("Sum_code");
					this.OnSum_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vc", DbType="Int")]
		public System.Nullable<int> Vc
		{
			get
			{
				return this._Vc;
			}
			set
			{
				if ((this._Vc != value))
				{
					this.OnVcChanging(value);
					this.SendPropertyChanging();
					this._Vc = value;
					this.SendPropertyChanged("Vc");
					this.OnVcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vr", DbType="Int")]
		public System.Nullable<int> Vr
		{
			get
			{
				return this._Vr;
			}
			set
			{
				if ((this._Vr != value))
				{
					this.OnVrChanging(value);
					this.SendPropertyChanging();
					this._Vr = value;
					this.SendPropertyChanged("Vr");
					this.OnVrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fr", DbType="Int")]
		public System.Nullable<int> Fr
		{
			get
			{
				return this._Fr;
			}
			set
			{
				if ((this._Fr != value))
				{
					this.OnFrChanging(value);
					this.SendPropertyChanging();
					this._Fr = value;
					this.SendPropertyChanged("Fr");
					this.OnFrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qr", DbType="Int")]
		public System.Nullable<int> Qr
		{
			get
			{
				return this._Qr;
			}
			set
			{
				if ((this._Qr != value))
				{
					this.OnQrChanging(value);
					this.SendPropertyChanging();
					this._Qr = value;
					this.SendPropertyChanged("Qr");
					this.OnQrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ca", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Ca
		{
			get
			{
				return this._Ca;
			}
			set
			{
				if ((this._Ca != value))
				{
					this.OnCaChanging(value);
					this.SendPropertyChanging();
					this._Ca = value;
					this.SendPropertyChanged("Ca");
					this.OnCaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iq1", DbType="Int")]
		public System.Nullable<int> Iq1
		{
			get
			{
				return this._Iq1;
			}
			set
			{
				if ((this._Iq1 != value))
				{
					this.OnIq1Changing(value);
					this.SendPropertyChanging();
					this._Iq1 = value;
					this.SendPropertyChanged("Iq1");
					this.OnIq1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iq2", DbType="Int")]
		public System.Nullable<int> Iq2
		{
			get
			{
				return this._Iq2;
			}
			set
			{
				if ((this._Iq2 != value))
				{
					this.OnIq2Changing(value);
					this.SendPropertyChanging();
					this._Iq2 = value;
					this.SendPropertyChanged("Iq2");
					this.OnIq2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iqs", DbType="Int")]
		public System.Nullable<int> Iqs
		{
			get
			{
				return this._Iqs;
			}
			set
			{
				if ((this._Iqs != value))
				{
					this.OnIqsChanging(value);
					this.SendPropertyChanging();
					this._Iqs = value;
					this.SendPropertyChanged("Iqs");
					this.OnIqsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iq12", DbType="Int")]
		public System.Nullable<int> Iq12
		{
			get
			{
				return this._Iq12;
			}
			set
			{
				if ((this._Iq12 != value))
				{
					this.OnIq12Changing(value);
					this.SendPropertyChanging();
					this._Iq12 = value;
					this.SendPropertyChanged("Iq12");
					this.OnIq12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iq22", DbType="Int")]
		public System.Nullable<int> Iq22
		{
			get
			{
				return this._Iq22;
			}
			set
			{
				if ((this._Iq22 != value))
				{
					this.OnIq22Changing(value);
					this.SendPropertyChanging();
					this._Iq22 = value;
					this.SendPropertyChanged("Iq22");
					this.OnIq22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iqs2", DbType="Int")]
		public System.Nullable<int> Iqs2
		{
			get
			{
				return this._Iqs2;
			}
			set
			{
				if ((this._Iqs2 != value))
				{
					this.OnIqs2Changing(value);
					this.SendPropertyChanging();
					this._Iqs2 = value;
					this.SendPropertyChanged("Iqs2");
					this.OnIqs2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vil", DbType="Int")]
		public System.Nullable<int> Vil
		{
			get
			{
				return this._Vil;
			}
			set
			{
				if ((this._Vil != value))
				{
					this.OnVilChanging(value);
					this.SendPropertyChanging();
					this._Vil = value;
					this.SendPropertyChanged("Vil");
					this.OnVilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vih", DbType="Int")]
		public System.Nullable<int> Vih
		{
			get
			{
				return this._Vih;
			}
			set
			{
				if ((this._Vih != value))
				{
					this.OnVihChanging(value);
					this.SendPropertyChanging();
					this._Vih = value;
					this.SendPropertyChanged("Vih");
					this.OnVihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vis", DbType="Int")]
		public System.Nullable<int> Vis
		{
			get
			{
				return this._Vis;
			}
			set
			{
				if ((this._Vis != value))
				{
					this.OnVisChanging(value);
					this.SendPropertyChanging();
					this._Vis = value;
					this.SendPropertyChanged("Vis");
					this.OnVisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nvil", DbType="Int")]
		public System.Nullable<int> Nvil
		{
			get
			{
				return this._Nvil;
			}
			set
			{
				if ((this._Nvil != value))
				{
					this.OnNvilChanging(value);
					this.SendPropertyChanging();
					this._Nvil = value;
					this.SendPropertyChanged("Nvil");
					this.OnNvilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nvih", DbType="Int")]
		public System.Nullable<int> Nvih
		{
			get
			{
				return this._Nvih;
			}
			set
			{
				if ((this._Nvih != value))
				{
					this.OnNvihChanging(value);
					this.SendPropertyChanging();
					this._Nvih = value;
					this.SendPropertyChanged("Nvih");
					this.OnNvihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nvis", DbType="Int")]
		public System.Nullable<int> Nvis
		{
			get
			{
				return this._Nvis;
			}
			set
			{
				if ((this._Nvis != value))
				{
					this.OnNvisChanging(value);
					this.SendPropertyChanging();
					this._Nvis = value;
					this.SendPropertyChanged("Nvis");
					this.OnNvisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mrs", DbType="Int")]
		public System.Nullable<int> Mrs
		{
			get
			{
				return this._Mrs;
			}
			set
			{
				if ((this._Mrs != value))
				{
					this.OnMrsChanging(value);
					this.SendPropertyChanging();
					this._Mrs = value;
					this.SendPropertyChanged("Mrs");
					this.OnMrsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mst", DbType="Int")]
		public System.Nullable<int> Mst
		{
			get
			{
				return this._Mst;
			}
			set
			{
				if ((this._Mst != value))
				{
					this.OnMstChanging(value);
					this.SendPropertyChanging();
					this._Mst = value;
					this.SendPropertyChanged("Mst");
					this.OnMstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prs", DbType="Int")]
		public System.Nullable<int> Prs
		{
			get
			{
				return this._Prs;
			}
			set
			{
				if ((this._Prs != value))
				{
					this.OnPrsChanging(value);
					this.SendPropertyChanging();
					this._Prs = value;
					this.SendPropertyChanged("Prs");
					this.OnPrsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pst", DbType="Int")]
		public System.Nullable<int> Pst
		{
			get
			{
				return this._Pst;
			}
			set
			{
				if ((this._Pst != value))
				{
					this.OnPstChanging(value);
					this.SendPropertyChanging();
					this._Pst = value;
					this.SendPropertyChanged("Pst");
					this.OnPstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rrs", DbType="Int")]
		public System.Nullable<int> Rrs
		{
			get
			{
				return this._Rrs;
			}
			set
			{
				if ((this._Rrs != value))
				{
					this.OnRrsChanging(value);
					this.SendPropertyChanging();
					this._Rrs = value;
					this.SendPropertyChanged("Rrs");
					this.OnRrsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rst", DbType="Int")]
		public System.Nullable<int> Rst
		{
			get
			{
				return this._Rst;
			}
			set
			{
				if ((this._Rst != value))
				{
					this.OnRstChanging(value);
					this.SendPropertyChanging();
					this._Rst = value;
					this.SendPropertyChanged("Rst");
					this.OnRstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ri1", DbType="Int")]
		public System.Nullable<int> Ri1
		{
			get
			{
				return this._Ri1;
			}
			set
			{
				if ((this._Ri1 != value))
				{
					this.OnRi1Changing(value);
					this.SendPropertyChanging();
					this._Ri1 = value;
					this.SendPropertyChanged("Ri1");
					this.OnRi1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ri2", DbType="Int")]
		public System.Nullable<int> Ri2
		{
			get
			{
				return this._Ri2;
			}
			set
			{
				if ((this._Ri2 != value))
				{
					this.OnRi2Changing(value);
					this.SendPropertyChanging();
					this._Ri2 = value;
					this.SendPropertyChanged("Ri2");
					this.OnRi2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Srs", DbType="Int")]
		public System.Nullable<int> Srs
		{
			get
			{
				return this._Srs;
			}
			set
			{
				if ((this._Srs != value))
				{
					this.OnSrsChanging(value);
					this.SendPropertyChanging();
					this._Srs = value;
					this.SendPropertyChanged("Srs");
					this.OnSrsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sst", DbType="Int")]
		public System.Nullable<int> Sst
		{
			get
			{
				return this._Sst;
			}
			set
			{
				if ((this._Sst != value))
				{
					this.OnSstChanging(value);
					this.SendPropertyChanging();
					this._Sst = value;
					this.SendPropertyChanged("Sst");
					this.OnSstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_We", DbType="Int")]
		public System.Nullable<int> We
		{
			get
			{
				return this._We;
			}
			set
			{
				if ((this._We != value))
				{
					this.OnWeChanging(value);
					this.SendPropertyChanging();
					this._We = value;
					this.SendPropertyChanged("We");
					this.OnWeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> Wr
		{
			get
			{
				return this._Wr;
			}
			set
			{
				if ((this._Wr != value))
				{
					this.OnWrChanging(value);
					this.SendPropertyChanging();
					this._Wr = value;
					this.SendPropertyChanged("Wr");
					this.OnWrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group]", Storage="_Group", DbType="VarChar(1)")]
		public string Group
		{
			get
			{
				return this._Group;
			}
			set
			{
				if ((this._Group != value))
				{
					this.OnGroupChanging(value);
					this.SendPropertyChanging();
					this._Group = value;
					this.SendPropertyChanged("Group");
					this.OnGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Math", DbType="Int")]
		public System.Nullable<int> Math
		{
			get
			{
				return this._Math;
			}
			set
			{
				if ((this._Math != value))
				{
					this.OnMathChanging(value);
					this.SendPropertyChanging();
					this._Math = value;
					this.SendPropertyChanged("Math");
					this.OnMathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lan_bas_sb", DbType="VarChar(1)")]
		public string Lan_bas_sb
		{
			get
			{
				return this._Lan_bas_sb;
			}
			set
			{
				if ((this._Lan_bas_sb != value))
				{
					this.OnLan_bas_sbChanging(value);
					this.SendPropertyChanging();
					this._Lan_bas_sb = value;
					this.SendPropertyChanged("Lan_bas_sb");
					this.OnLan_bas_sbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum_code_r", DbType="VarChar(3)")]
		public string Sum_code_r
		{
			get
			{
				return this._Sum_code_r;
			}
			set
			{
				if ((this._Sum_code_r != value))
				{
					this.OnSum_code_rChanging(value);
					this.SendPropertyChanging();
					this._Sum_code_r = value;
					this.SendPropertyChanged("Sum_code_r");
					this.OnSum_code_rChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum_code_a", DbType="VarChar(3)")]
		public string Sum_code_a
		{
			get
			{
				return this._Sum_code_a;
			}
			set
			{
				if ((this._Sum_code_a != value))
				{
					this.OnSum_code_aChanging(value);
					this.SendPropertyChanging();
					this._Sum_code_a = value;
					this.SendPropertyChanged("Sum_code_a");
					this.OnSum_code_aChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum_code_s", DbType="VarChar(3)")]
		public string Sum_code_s
		{
			get
			{
				return this._Sum_code_s;
			}
			set
			{
				if ((this._Sum_code_s != value))
				{
					this.OnSum_code_sChanging(value);
					this.SendPropertyChanging();
					this._Sum_code_s = value;
					this.SendPropertyChanged("Sum_code_s");
					this.OnSum_code_sChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum_code_i", DbType="VarChar(3)")]
		public string Sum_code_i
		{
			get
			{
				return this._Sum_code_i;
			}
			set
			{
				if ((this._Sum_code_i != value))
				{
					this.OnSum_code_iChanging(value);
					this.SendPropertyChanging();
					this._Sum_code_i = value;
					this.SendPropertyChanged("Sum_code_i");
					this.OnSum_code_iChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum_code_c", DbType="VarChar(3)")]
		public string Sum_code_c
		{
			get
			{
				return this._Sum_code_c;
			}
			set
			{
				if ((this._Sum_code_c != value))
				{
					this.OnSum_code_cChanging(value);
					this.SendPropertyChanging();
					this._Sum_code_c = value;
					this.SendPropertyChanged("Sum_code_c");
					this.OnSum_code_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum_code_e", DbType="VarChar(3)")]
		public string Sum_code_e
		{
			get
			{
				return this._Sum_code_e;
			}
			set
			{
				if ((this._Sum_code_e != value))
				{
					this.OnSum_code_eChanging(value);
					this.SendPropertyChanging();
					this._Sum_code_e = value;
					this.SendPropertyChanged("Sum_code_e");
					this.OnSum_code_eChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Char_wrk_m", DbType="Int")]
		public System.Nullable<int> Char_wrk_m
		{
			get
			{
				return this._Char_wrk_m;
			}
			set
			{
				if ((this._Char_wrk_m != value))
				{
					this.OnChar_wrk_mChanging(value);
					this.SendPropertyChanging();
					this._Char_wrk_m = value;
					this.SendPropertyChanged("Char_wrk_m");
					this.OnChar_wrk_mChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Char_wrk_s", DbType="Int")]
		public System.Nullable<int> Char_wrk_s
		{
			get
			{
				return this._Char_wrk_s;
			}
			set
			{
				if ((this._Char_wrk_s != value))
				{
					this.OnChar_wrk_sChanging(value);
					this.SendPropertyChanging();
					this._Char_wrk_s = value;
					this.SendPropertyChanged("Char_wrk_s");
					this.OnChar_wrk_sChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Char_wrk_d", DbType="Int")]
		public System.Nullable<int> Char_wrk_d
		{
			get
			{
				return this._Char_wrk_d;
			}
			set
			{
				if ((this._Char_wrk_d != value))
				{
					this.OnChar_wrk_dChanging(value);
					this.SendPropertyChanging();
					this._Char_wrk_d = value;
					this.SendPropertyChanged("Char_wrk_d");
					this.OnChar_wrk_dChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Car_aware", DbType="Int")]
		public System.Nullable<int> Car_aware
		{
			get
			{
				return this._Car_aware;
			}
			set
			{
				if ((this._Car_aware != value))
				{
					this.OnCar_awareChanging(value);
					this.SendPropertyChanging();
					this._Car_aware = value;
					this.SendPropertyChanged("Car_aware");
					this.OnCar_awareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice1", DbType="VarChar(1)")]
		public string Choice1
		{
			get
			{
				return this._Choice1;
			}
			set
			{
				if ((this._Choice1 != value))
				{
					this.OnChoice1Changing(value);
					this.SendPropertyChanging();
					this._Choice1 = value;
					this.SendPropertyChanged("Choice1");
					this.OnChoice1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice2", DbType="VarChar(1)")]
		public string Choice2
		{
			get
			{
				return this._Choice2;
			}
			set
			{
				if ((this._Choice2 != value))
				{
					this.OnChoice2Changing(value);
					this.SendPropertyChanging();
					this._Choice2 = value;
					this.SendPropertyChanged("Choice2");
					this.OnChoice2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice3", DbType="VarChar(1)")]
		public string Choice3
		{
			get
			{
				return this._Choice3;
			}
			set
			{
				if ((this._Choice3 != value))
				{
					this.OnChoice3Changing(value);
					this.SendPropertyChanging();
					this._Choice3 = value;
					this.SendPropertyChanged("Choice3");
					this.OnChoice3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_id", DbType="VarChar(20)")]
		public string Student_id
		{
			get
			{
				return this._Student_id;
			}
			set
			{
				if ((this._Student_id != value))
				{
					this.OnStudent_idChanging(value);
					this.SendPropertyChanging();
					this._Student_id = value;
					this.SendPropertyChanged("Student_id");
					this.OnStudent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Csv_genab", DbType="VarChar(130)")]
		public string Csv_genab
		{
			get
			{
				return this._Csv_genab;
			}
			set
			{
				if ((this._Csv_genab != value))
				{
					this.OnCsv_genabChanging(value);
					this.SendPropertyChanging();
					this._Csv_genab = value;
					this.SendPropertyChanged("Csv_genab");
					this.OnCsv_genabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Csv_read", DbType="VarChar(70)")]
		public string Csv_read
		{
			get
			{
				return this._Csv_read;
			}
			set
			{
				if ((this._Csv_read != value))
				{
					this.OnCsv_readChanging(value);
					this.SendPropertyChanging();
					this._Csv_read = value;
					this.SendPropertyChanged("Csv_read");
					this.OnCsv_readChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Csv_math", DbType="VarChar(60)")]
		public string Csv_math
		{
			get
			{
				return this._Csv_math;
			}
			set
			{
				if ((this._Csv_math != value))
				{
					this.OnCsv_mathChanging(value);
					this.SendPropertyChanging();
					this._Csv_math = value;
					this.SendPropertyChanged("Csv_math");
					this.OnCsv_mathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Csv_spell", DbType="VarChar(40)")]
		public string Csv_spell
		{
			get
			{
				return this._Csv_spell;
			}
			set
			{
				if ((this._Csv_spell != value))
				{
					this.OnCsv_spellChanging(value);
					this.SendPropertyChanging();
					this._Csv_spell = value;
					this.SendPropertyChanged("Csv_spell");
					this.OnCsv_spellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_genab", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> S_genab
		{
			get
			{
				return this._S_genab;
			}
			set
			{
				if ((this._S_genab != value))
				{
					this.OnS_genabChanging(value);
					this.SendPropertyChanging();
					this._S_genab = value;
					this.SendPropertyChanged("S_genab");
					this.OnS_genabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_verbal", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> S_verbal
		{
			get
			{
				return this._S_verbal;
			}
			set
			{
				if ((this._S_verbal != value))
				{
					this.OnS_verbalChanging(value);
					this.SendPropertyChanging();
					this._S_verbal = value;
					this.SendPropertyChanged("S_verbal");
					this.OnS_verbalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_nonverb", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> S_nonverb
		{
			get
			{
				return this._S_nonverb;
			}
			set
			{
				if ((this._S_nonverb != value))
				{
					this.OnS_nonverbChanging(value);
					this.SendPropertyChanging();
					this._S_nonverb = value;
					this.SendPropertyChanged("S_nonverb");
					this.OnS_nonverbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_mathper", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> S_mathper
		{
			get
			{
				return this._S_mathper;
			}
			set
			{
				if ((this._S_mathper != value))
				{
					this.OnS_mathperChanging(value);
					this.SendPropertyChanging();
					this._S_mathper = value;
					this.SendPropertyChanged("S_mathper");
					this.OnS_mathperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_reading", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> S_reading
		{
			get
			{
				return this._S_reading;
			}
			set
			{
				if ((this._S_reading != value))
				{
					this.OnS_readingChanging(value);
					this.SendPropertyChanging();
					this._S_reading = value;
					this.SendPropertyChanged("S_reading");
					this.OnS_readingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_written", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> S_written
		{
			get
			{
				return this._S_written;
			}
			set
			{
				if ((this._S_written != value))
				{
					this.OnS_writtenChanging(value);
					this.SendPropertyChanging();
					this._S_written = value;
					this.SendPropertyChanged("S_written");
					this.OnS_writtenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_spelling", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> S_spelling
		{
			get
			{
				return this._S_spelling;
			}
			set
			{
				if ((this._S_spelling != value))
				{
					this.OnS_spellingChanging(value);
					this.SendPropertyChanging();
					this._S_spelling = value;
					this.SendPropertyChanged("S_spelling");
					this.OnS_spellingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fkg", DbType="Bit")]
		public System.Nullable<bool> Fkg
		{
			get
			{
				return this._Fkg;
			}
			set
			{
				if ((this._Fkg != value))
				{
					this.OnFkgChanging(value);
					this.SendPropertyChanging();
					this._Fkg = value;
					this.SendPropertyChanged("Fkg");
					this.OnFkgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edu_plan", DbType="VarChar(1)")]
		public string Edu_plan
		{
			get
			{
				return this._Edu_plan;
			}
			set
			{
				if ((this._Edu_plan != value))
				{
					this.OnEdu_planChanging(value);
					this.SendPropertyChanging();
					this._Edu_plan = value;
					this.SendPropertyChanged("Edu_plan");
					this.OnEdu_planChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Custom1", DbType="VarChar(100)")]
		public string Custom1
		{
			get
			{
				return this._Custom1;
			}
			set
			{
				if ((this._Custom1 != value))
				{
					this.OnCustom1Changing(value);
					this.SendPropertyChanging();
					this._Custom1 = value;
					this.SendPropertyChanged("Custom1");
					this.OnCustom1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntStudent", DbType="VarChar(1)")]
		public string IntStudent
		{
			get
			{
				return this._IntStudent;
			}
			set
			{
				if ((this._IntStudent != value))
				{
					this.OnIntStudentChanging(value);
					this.SendPropertyChanging();
					this._IntStudent = value;
					this.SendPropertyChanged("IntStudent");
					this.OnIntStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form_mod", DbType="VarChar(1)")]
		public string Form_mod
		{
			get
			{
				return this._Form_mod;
			}
			set
			{
				if ((this._Form_mod != value))
				{
					this.OnForm_modChanging(value);
					this.SendPropertyChanging();
					this._Form_mod = value;
					this.SendPropertyChanged("Form_mod");
					this.OnForm_modChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewWr", DbType="Int")]
		public System.Nullable<int> NewWr
		{
			get
			{
				return this._NewWr;
			}
			set
			{
				if ((this._NewWr != value))
				{
					this.OnNewWrChanging(value);
					this.SendPropertyChanging();
					this._NewWr = value;
					this.SendPropertyChanged("NewWr");
					this.OnNewWrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wrt", DbType="Int")]
		public System.Nullable<int> Wrt
		{
			get
			{
				return this._Wrt;
			}
			set
			{
				if ((this._Wrt != value))
				{
					this.OnWrtChanging(value);
					this.SendPropertyChanging();
					this._Wrt = value;
					this.SendPropertyChanged("Wrt");
					this.OnWrtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_csv_writing", DbType="VarChar(40)")]
		public string csv_writing
		{
			get
			{
				return this._csv_writing;
			}
			set
			{
				if ((this._csv_writing != value))
				{
					this.Oncsv_writingChanging(value);
					this.SendPropertyChanging();
					this._csv_writing = value;
					this.SendPropertyChanged("csv_writing");
					this.Oncsv_writingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_genab", DbType="Int")]
		public System.Nullable<int> t_genab
		{
			get
			{
				return this._t_genab;
			}
			set
			{
				if ((this._t_genab != value))
				{
					this.Ont_genabChanging(value);
					this.SendPropertyChanging();
					this._t_genab = value;
					this.SendPropertyChanged("t_genab");
					this.Ont_genabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_verbal", DbType="Int")]
		public System.Nullable<int> t_verbal
		{
			get
			{
				return this._t_verbal;
			}
			set
			{
				if ((this._t_verbal != value))
				{
					this.Ont_verbalChanging(value);
					this.SendPropertyChanging();
					this._t_verbal = value;
					this.SendPropertyChanged("t_verbal");
					this.Ont_verbalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_nverbal", DbType="Int")]
		public System.Nullable<int> t_nverbal
		{
			get
			{
				return this._t_nverbal;
			}
			set
			{
				if ((this._t_nverbal != value))
				{
					this.Ont_nverbalChanging(value);
					this.SendPropertyChanging();
					this._t_nverbal = value;
					this.SendPropertyChanged("t_nverbal");
					this.Ont_nverbalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_pst", DbType="Int")]
		public System.Nullable<int> t_pst
		{
			get
			{
				return this._t_pst;
			}
			set
			{
				if ((this._t_pst != value))
				{
					this.Ont_pstChanging(value);
					this.SendPropertyChanging();
					this._t_pst = value;
					this.SendPropertyChanged("t_pst");
					this.Ont_pstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_rst", DbType="Int")]
		public System.Nullable<int> t_rst
		{
			get
			{
				return this._t_rst;
			}
			set
			{
				if ((this._t_rst != value))
				{
					this.Ont_rstChanging(value);
					this.SendPropertyChanging();
					this._t_rst = value;
					this.SendPropertyChanged("t_rst");
					this.Ont_rstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_sst", DbType="Int")]
		public System.Nullable<int> t_sst
		{
			get
			{
				return this._t_sst;
			}
			set
			{
				if ((this._t_sst != value))
				{
					this.Ont_sstChanging(value);
					this.SendPropertyChanging();
					this._t_sst = value;
					this.SendPropertyChanged("t_sst");
					this.Ont_sstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_wr", DbType="Int")]
		public System.Nullable<int> t_wr
		{
			get
			{
				return this._t_wr;
			}
			set
			{
				if ((this._t_wr != value))
				{
					this.Ont_wrChanging(value);
					this.SendPropertyChanging();
					this._t_wr = value;
					this.SendPropertyChanged("t_wr");
					this.Ont_wrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_mst", DbType="Int")]
		public System.Nullable<int> t_mst
		{
			get
			{
				return this._t_mst;
			}
			set
			{
				if ((this._t_mst != value))
				{
					this.Ont_mstChanging(value);
					this.SendPropertyChanging();
					this._t_mst = value;
					this.SendPropertyChanged("t_mst");
					this.Ont_mstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serialno", DbType="Int")]
		public System.Nullable<int> Serialno
		{
			get
			{
				return this._Serialno;
			}
			set
			{
				if ((this._Serialno != value))
				{
					this.OnSerialnoChanging(value);
					this.SendPropertyChanging();
					this._Serialno = value;
					this.SendPropertyChanged("Serialno");
					this.OnSerialnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_task", DbType="VarChar(1)")]
		public string Wr_task
		{
			get
			{
				return this._Wr_task;
			}
			set
			{
				if ((this._Wr_task != value))
				{
					this.OnWr_taskChanging(value);
					this.SendPropertyChanging();
					this._Wr_task = value;
					this.SendPropertyChanged("Wr_task");
					this.OnWr_taskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_genre", DbType="SmallInt")]
		public System.Nullable<short> Wr_genre
		{
			get
			{
				return this._Wr_genre;
			}
			set
			{
				if ((this._Wr_genre != value))
				{
					this.OnWr_genreChanging(value);
					this.SendPropertyChanging();
					this._Wr_genre = value;
					this.SendPropertyChanged("Wr_genre");
					this.OnWr_genreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_args", DbType="SmallInt")]
		public System.Nullable<short> Wr_args
		{
			get
			{
				return this._Wr_args;
			}
			set
			{
				if ((this._Wr_args != value))
				{
					this.OnWr_argsChanging(value);
					this.SendPropertyChanging();
					this._Wr_args = value;
					this.SendPropertyChanged("Wr_args");
					this.OnWr_argsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_rhtdev", DbType="SmallInt")]
		public System.Nullable<short> Wr_rhtdev
		{
			get
			{
				return this._Wr_rhtdev;
			}
			set
			{
				if ((this._Wr_rhtdev != value))
				{
					this.OnWr_rhtdevChanging(value);
					this.SendPropertyChanging();
					this._Wr_rhtdev = value;
					this.SendPropertyChanged("Wr_rhtdev");
					this.OnWr_rhtdevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_nardev", DbType="SmallInt")]
		public System.Nullable<short> Wr_nardev
		{
			get
			{
				return this._Wr_nardev;
			}
			set
			{
				if ((this._Wr_nardev != value))
				{
					this.OnWr_nardevChanging(value);
					this.SendPropertyChanging();
					this._Wr_nardev = value;
					this.SendPropertyChanged("Wr_nardev");
					this.OnWr_nardevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_thmdev", DbType="SmallInt")]
		public System.Nullable<short> Wr_thmdev
		{
			get
			{
				return this._Wr_thmdev;
			}
			set
			{
				if ((this._Wr_thmdev != value))
				{
					this.OnWr_thmdevChanging(value);
					this.SendPropertyChanging();
					this._Wr_thmdev = value;
					this.SendPropertyChanged("Wr_thmdev");
					this.OnWr_thmdevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_vocab", DbType="SmallInt")]
		public System.Nullable<short> Wr_vocab
		{
			get
			{
				return this._Wr_vocab;
			}
			set
			{
				if ((this._Wr_vocab != value))
				{
					this.OnWr_vocabChanging(value);
					this.SendPropertyChanging();
					this._Wr_vocab = value;
					this.SendPropertyChanged("Wr_vocab");
					this.OnWr_vocabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_senstr", DbType="SmallInt")]
		public System.Nullable<short> Wr_senstr
		{
			get
			{
				return this._Wr_senstr;
			}
			set
			{
				if ((this._Wr_senstr != value))
				{
					this.OnWr_senstrChanging(value);
					this.SendPropertyChanging();
					this._Wr_senstr = value;
					this.SendPropertyChanged("Wr_senstr");
					this.OnWr_senstrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_synten", DbType="SmallInt")]
		public System.Nullable<short> Wr_synten
		{
			get
			{
				return this._Wr_synten;
			}
			set
			{
				if ((this._Wr_synten != value))
				{
					this.OnWr_syntenChanging(value);
					this.SendPropertyChanging();
					this._Wr_synten = value;
					this.SendPropertyChanged("Wr_synten");
					this.OnWr_syntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_punct", DbType="SmallInt")]
		public System.Nullable<short> Wr_punct
		{
			get
			{
				return this._Wr_punct;
			}
			set
			{
				if ((this._Wr_punct != value))
				{
					this.OnWr_punctChanging(value);
					this.SendPropertyChanging();
					this._Wr_punct = value;
					this.SendPropertyChanged("Wr_punct");
					this.OnWr_punctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_spell", DbType="SmallInt")]
		public System.Nullable<short> Wr_spell
		{
			get
			{
				return this._Wr_spell;
			}
			set
			{
				if ((this._Wr_spell != value))
				{
					this.OnWr_spellChanging(value);
					this.SendPropertyChanging();
					this._Wr_spell = value;
					this.SendPropertyChanged("Wr_spell");
					this.OnWr_spellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_level", DbType="SmallInt")]
		public System.Nullable<short> Wr_level
		{
			get
			{
				return this._Wr_level;
			}
			set
			{
				if ((this._Wr_level != value))
				{
					this.OnWr_levelChanging(value);
					this.SendPropertyChanging();
					this._Wr_level = value;
					this.SendPropertyChanged("Wr_level");
					this.OnWr_levelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wr_sem", DbType="SmallInt")]
		public System.Nullable<short> Wr_sem
		{
			get
			{
				return this._Wr_sem;
			}
			set
			{
				if ((this._Wr_sem != value))
				{
					this.OnWr_semChanging(value);
					this.SendPropertyChanging();
					this._Wr_sem = value;
					this.SendPropertyChanged("Wr_sem");
					this.OnWr_semChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Char_wrk_i", DbType="Int")]
		public System.Nullable<int> Char_wrk_i
		{
			get
			{
				return this._Char_wrk_i;
			}
			set
			{
				if ((this._Char_wrk_i != value))
				{
					this.OnChar_wrk_iChanging(value);
					this.SendPropertyChanging();
					this._Char_wrk_i = value;
					this.SendPropertyChanged("Char_wrk_i");
					this.OnChar_wrk_iChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genabcor", DbType="VarChar(130)")]
		public string Genabcor
		{
			get
			{
				return this._Genabcor;
			}
			set
			{
				if ((this._Genabcor != value))
				{
					this.OnGenabcorChanging(value);
					this.SendPropertyChanging();
					this._Genabcor = value;
					this.SendPropertyChanged("Genabcor");
					this.OnGenabcorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spellcor", DbType="VarChar(100)")]
		public string Spellcor
		{
			get
			{
				return this._Spellcor;
			}
			set
			{
				if ((this._Spellcor != value))
				{
					this.OnSpellcorChanging(value);
					this.SendPropertyChanging();
					this._Spellcor = value;
					this.SendPropertyChanged("Spellcor");
					this.OnSpellcorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Readcor", DbType="VarChar(100)")]
		public string Readcor
		{
			get
			{
				return this._Readcor;
			}
			set
			{
				if ((this._Readcor != value))
				{
					this.OnReadcorChanging(value);
					this.SendPropertyChanging();
					this._Readcor = value;
					this.SendPropertyChanged("Readcor");
					this.OnReadcorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalStudentId", DbType="Int")]
		public System.Nullable<int> GlobalStudentId
		{
			get
			{
				return this._GlobalStudentId;
			}
			set
			{
				if ((this._GlobalStudentId != value))
				{
					this.OnGlobalStudentIdChanging(value);
					this.SendPropertyChanging();
					this._GlobalStudentId = value;
					this.SendPropertyChanged("GlobalStudentId");
					this.OnGlobalStudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolPref1", DbType="VarChar(120)")]
		public string SchoolPref1
		{
			get
			{
				return this._SchoolPref1;
			}
			set
			{
				if ((this._SchoolPref1 != value))
				{
					this.OnSchoolPref1Changing(value);
					this.SendPropertyChanging();
					this._SchoolPref1 = value;
					this.SendPropertyChanged("SchoolPref1");
					this.OnSchoolPref1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolPref2", DbType="VarChar(120)")]
		public string SchoolPref2
		{
			get
			{
				return this._SchoolPref2;
			}
			set
			{
				if ((this._SchoolPref2 != value))
				{
					this.OnSchoolPref2Changing(value);
					this.SendPropertyChanging();
					this._SchoolPref2 = value;
					this.SendPropertyChanged("SchoolPref2");
					this.OnSchoolPref2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolPref3", DbType="VarChar(120)")]
		public string SchoolPref3
		{
			get
			{
				return this._SchoolPref3;
			}
			set
			{
				if ((this._SchoolPref3 != value))
				{
					this.OnSchoolPref3Changing(value);
					this.SendPropertyChanging();
					this._SchoolPref3 = value;
					this.SendPropertyChanged("SchoolPref3");
					this.OnSchoolPref3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolPref4", DbType="VarChar(120)")]
		public string SchoolPref4
		{
			get
			{
				return this._SchoolPref4;
			}
			set
			{
				if ((this._SchoolPref4 != value))
				{
					this.OnSchoolPref4Changing(value);
					this.SendPropertyChanging();
					this._SchoolPref4 = value;
					this.SendPropertyChanged("SchoolPref4");
					this.OnSchoolPref4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolPref5", DbType="VarChar(120)")]
		public string SchoolPref5
		{
			get
			{
				return this._SchoolPref5;
			}
			set
			{
				if ((this._SchoolPref5 != value))
				{
					this.OnSchoolPref5Changing(value);
					this.SendPropertyChanging();
					this._SchoolPref5 = value;
					this.SendPropertyChanged("SchoolPref5");
					this.OnSchoolPref5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScholarshipApplicantId", DbType="Int")]
		public System.Nullable<int> ScholarshipApplicantId
		{
			get
			{
				return this._ScholarshipApplicantId;
			}
			set
			{
				if ((this._ScholarshipApplicantId != value))
				{
					this.OnScholarshipApplicantIdChanging(value);
					this.SendPropertyChanging();
					this._ScholarshipApplicantId = value;
					this.SendPropertyChanged("ScholarshipApplicantId");
					this.OnScholarshipApplicantIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Npi_Read", DbType="SmallInt")]
		public System.Nullable<short> Npi_Read
		{
			get
			{
				return this._Npi_Read;
			}
			set
			{
				if ((this._Npi_Read != value))
				{
					this.OnNpi_ReadChanging(value);
					this.SendPropertyChanging();
					this._Npi_Read = value;
					this.SendPropertyChanged("Npi_Read");
					this.OnNpi_ReadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Npi_Math", DbType="SmallInt")]
		public System.Nullable<short> Npi_Math
		{
			get
			{
				return this._Npi_Math;
			}
			set
			{
				if ((this._Npi_Math != value))
				{
					this.OnNpi_MathChanging(value);
					this.SendPropertyChanging();
					this._Npi_Math = value;
					this.SendPropertyChanged("Npi_Math");
					this.OnNpi_MathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Npi_Writing", DbType="SmallInt")]
		public System.Nullable<short> Npi_Writing
		{
			get
			{
				return this._Npi_Writing;
			}
			set
			{
				if ((this._Npi_Writing != value))
				{
					this.OnNpi_WritingChanging(value);
					this.SendPropertyChanging();
					this._Npi_Writing = value;
					this.SendPropertyChanged("Npi_Writing");
					this.OnNpi_WritingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Published", DbType="DateTime")]
		public System.Nullable<System.DateTime> Published
		{
			get
			{
				return this._Published;
			}
			set
			{
				if ((this._Published != value))
				{
					this.OnPublishedChanging(value);
					this.SendPropertyChanging();
					this._Published = value;
					this.SendPropertyChanged("Published");
					this.OnPublishedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tests")]
	public partial class Test : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Testnum;
		
		private string _Answer;
		
		private string _Type;
		
		private string _Category;
		
		private int _Scode;
		
		private string _State;
		
		private int _Tested;
		
		private System.DateTime _Testdate;
		
		private int _Grade;
		
		private string _NameGrade;
		
		private string _ReadingDb;
		
		private System.Nullable<int> _Nq_genab;
		
		private System.Nullable<int> _Nq_verbal;
		
		private System.Nullable<int> _Nq_nonverb;
		
		private System.Nullable<int> _Nq_maths;
		
		private System.Nullable<int> _Nq_read;
		
		private System.Nullable<int> _Nq_spell;
		
		private System.Nullable<int> _Nq_written;
		
		private System.Nullable<System.DateTime> _Published;
		
		private System.Nullable<int> _MathProfileId;
		
		private System.Nullable<int> _ReadProfileId;
		
		private System.Nullable<int> _NpiReadingId;
		
		private System.Nullable<int> _NpiWritingId;
		
		private System.Nullable<int> _NpiMathId;
		
		private System.Nullable<short> _NpiReadingMeanCalculation;
		
		private System.Nullable<short> _NpiWritingMeanCalculation;
		
		private System.Nullable<short> _NpiMathMeanCalculation;
		
		private bool _HasScholarshipInfo;
		
		private bool _IsGroupSchools;
		
		private string _PublishedBy;
		
		private System.Nullable<bool> _InternalUse;
		
		private bool _Hidden;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTestnumChanging(int value);
    partial void OnTestnumChanged();
    partial void OnAnswerChanging(string value);
    partial void OnAnswerChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnScodeChanging(int value);
    partial void OnScodeChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnTestedChanging(int value);
    partial void OnTestedChanged();
    partial void OnTestdateChanging(System.DateTime value);
    partial void OnTestdateChanged();
    partial void OnGradeChanging(int value);
    partial void OnGradeChanged();
    partial void OnNameGradeChanging(string value);
    partial void OnNameGradeChanged();
    partial void OnReadingDbChanging(string value);
    partial void OnReadingDbChanged();
    partial void OnNq_genabChanging(System.Nullable<int> value);
    partial void OnNq_genabChanged();
    partial void OnNq_verbalChanging(System.Nullable<int> value);
    partial void OnNq_verbalChanged();
    partial void OnNq_nonverbChanging(System.Nullable<int> value);
    partial void OnNq_nonverbChanged();
    partial void OnNq_mathsChanging(System.Nullable<int> value);
    partial void OnNq_mathsChanged();
    partial void OnNq_readChanging(System.Nullable<int> value);
    partial void OnNq_readChanged();
    partial void OnNq_spellChanging(System.Nullable<int> value);
    partial void OnNq_spellChanged();
    partial void OnNq_writtenChanging(System.Nullable<int> value);
    partial void OnNq_writtenChanged();
    partial void OnPublishedChanging(System.Nullable<System.DateTime> value);
    partial void OnPublishedChanged();
    partial void OnMathProfileIdChanging(System.Nullable<int> value);
    partial void OnMathProfileIdChanged();
    partial void OnReadProfileIdChanging(System.Nullable<int> value);
    partial void OnReadProfileIdChanged();
    partial void OnNpiReadingIdChanging(System.Nullable<int> value);
    partial void OnNpiReadingIdChanged();
    partial void OnNpiWritingIdChanging(System.Nullable<int> value);
    partial void OnNpiWritingIdChanged();
    partial void OnNpiMathIdChanging(System.Nullable<int> value);
    partial void OnNpiMathIdChanged();
    partial void OnNpiReadingMeanCalculationChanging(System.Nullable<short> value);
    partial void OnNpiReadingMeanCalculationChanged();
    partial void OnNpiWritingMeanCalculationChanging(System.Nullable<short> value);
    partial void OnNpiWritingMeanCalculationChanged();
    partial void OnNpiMathMeanCalculationChanging(System.Nullable<short> value);
    partial void OnNpiMathMeanCalculationChanged();
    partial void OnHasScholarshipInfoChanging(bool value);
    partial void OnHasScholarshipInfoChanged();
    partial void OnIsGroupSchoolsChanging(bool value);
    partial void OnIsGroupSchoolsChanged();
    partial void OnPublishedByChanging(string value);
    partial void OnPublishedByChanged();
    partial void OnInternalUseChanging(System.Nullable<bool> value);
    partial void OnInternalUseChanged();
    partial void OnHiddenChanging(bool value);
    partial void OnHiddenChanged();
    #endregion
		
		public Test()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Testnum", DbType="Int NOT NULL")]
		public int Testnum
		{
			get
			{
				return this._Testnum;
			}
			set
			{
				if ((this._Testnum != value))
				{
					this.OnTestnumChanging(value);
					this.SendPropertyChanging();
					this._Testnum = value;
					this.SendPropertyChanged("Testnum");
					this.OnTestnumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this.OnAnswerChanging(value);
					this.SendPropertyChanging();
					this._Answer = value;
					this.SendPropertyChanged("Answer");
					this.OnAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(40)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scode", DbType="Int NOT NULL")]
		public int Scode
		{
			get
			{
				return this._Scode;
			}
			set
			{
				if ((this._Scode != value))
				{
					this.OnScodeChanging(value);
					this.SendPropertyChanging();
					this._Scode = value;
					this.SendPropertyChanged("Scode");
					this.OnScodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(3)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tested", DbType="Int NOT NULL")]
		public int Tested
		{
			get
			{
				return this._Tested;
			}
			set
			{
				if ((this._Tested != value))
				{
					this.OnTestedChanging(value);
					this.SendPropertyChanging();
					this._Tested = value;
					this.SendPropertyChanged("Tested");
					this.OnTestedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Testdate", DbType="DateTime NOT NULL")]
		public System.DateTime Testdate
		{
			get
			{
				return this._Testdate;
			}
			set
			{
				if ((this._Testdate != value))
				{
					this.OnTestdateChanging(value);
					this.SendPropertyChanging();
					this._Testdate = value;
					this.SendPropertyChanged("Testdate");
					this.OnTestdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="Int NOT NULL")]
		public int Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this.OnGradeChanging(value);
					this.SendPropertyChanging();
					this._Grade = value;
					this.SendPropertyChanged("Grade");
					this.OnGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameGrade", DbType="VarChar(5)")]
		public string NameGrade
		{
			get
			{
				return this._NameGrade;
			}
			set
			{
				if ((this._NameGrade != value))
				{
					this.OnNameGradeChanging(value);
					this.SendPropertyChanging();
					this._NameGrade = value;
					this.SendPropertyChanged("NameGrade");
					this.OnNameGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadingDb", DbType="VarChar(10)")]
		public string ReadingDb
		{
			get
			{
				return this._ReadingDb;
			}
			set
			{
				if ((this._ReadingDb != value))
				{
					this.OnReadingDbChanging(value);
					this.SendPropertyChanging();
					this._ReadingDb = value;
					this.SendPropertyChanged("ReadingDb");
					this.OnReadingDbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nq_genab", DbType="Int")]
		public System.Nullable<int> Nq_genab
		{
			get
			{
				return this._Nq_genab;
			}
			set
			{
				if ((this._Nq_genab != value))
				{
					this.OnNq_genabChanging(value);
					this.SendPropertyChanging();
					this._Nq_genab = value;
					this.SendPropertyChanged("Nq_genab");
					this.OnNq_genabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nq_verbal", DbType="Int")]
		public System.Nullable<int> Nq_verbal
		{
			get
			{
				return this._Nq_verbal;
			}
			set
			{
				if ((this._Nq_verbal != value))
				{
					this.OnNq_verbalChanging(value);
					this.SendPropertyChanging();
					this._Nq_verbal = value;
					this.SendPropertyChanged("Nq_verbal");
					this.OnNq_verbalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nq_nonverb", DbType="Int")]
		public System.Nullable<int> Nq_nonverb
		{
			get
			{
				return this._Nq_nonverb;
			}
			set
			{
				if ((this._Nq_nonverb != value))
				{
					this.OnNq_nonverbChanging(value);
					this.SendPropertyChanging();
					this._Nq_nonverb = value;
					this.SendPropertyChanged("Nq_nonverb");
					this.OnNq_nonverbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nq_maths", DbType="Int")]
		public System.Nullable<int> Nq_maths
		{
			get
			{
				return this._Nq_maths;
			}
			set
			{
				if ((this._Nq_maths != value))
				{
					this.OnNq_mathsChanging(value);
					this.SendPropertyChanging();
					this._Nq_maths = value;
					this.SendPropertyChanged("Nq_maths");
					this.OnNq_mathsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nq_read", DbType="Int")]
		public System.Nullable<int> Nq_read
		{
			get
			{
				return this._Nq_read;
			}
			set
			{
				if ((this._Nq_read != value))
				{
					this.OnNq_readChanging(value);
					this.SendPropertyChanging();
					this._Nq_read = value;
					this.SendPropertyChanged("Nq_read");
					this.OnNq_readChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nq_spell", DbType="Int")]
		public System.Nullable<int> Nq_spell
		{
			get
			{
				return this._Nq_spell;
			}
			set
			{
				if ((this._Nq_spell != value))
				{
					this.OnNq_spellChanging(value);
					this.SendPropertyChanging();
					this._Nq_spell = value;
					this.SendPropertyChanged("Nq_spell");
					this.OnNq_spellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nq_written", DbType="Int")]
		public System.Nullable<int> Nq_written
		{
			get
			{
				return this._Nq_written;
			}
			set
			{
				if ((this._Nq_written != value))
				{
					this.OnNq_writtenChanging(value);
					this.SendPropertyChanging();
					this._Nq_written = value;
					this.SendPropertyChanged("Nq_written");
					this.OnNq_writtenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Published", DbType="DateTime")]
		public System.Nullable<System.DateTime> Published
		{
			get
			{
				return this._Published;
			}
			set
			{
				if ((this._Published != value))
				{
					this.OnPublishedChanging(value);
					this.SendPropertyChanging();
					this._Published = value;
					this.SendPropertyChanged("Published");
					this.OnPublishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MathProfileId", DbType="Int")]
		public System.Nullable<int> MathProfileId
		{
			get
			{
				return this._MathProfileId;
			}
			set
			{
				if ((this._MathProfileId != value))
				{
					this.OnMathProfileIdChanging(value);
					this.SendPropertyChanging();
					this._MathProfileId = value;
					this.SendPropertyChanged("MathProfileId");
					this.OnMathProfileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadProfileId", DbType="Int")]
		public System.Nullable<int> ReadProfileId
		{
			get
			{
				return this._ReadProfileId;
			}
			set
			{
				if ((this._ReadProfileId != value))
				{
					this.OnReadProfileIdChanging(value);
					this.SendPropertyChanging();
					this._ReadProfileId = value;
					this.SendPropertyChanged("ReadProfileId");
					this.OnReadProfileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NpiReadingId", DbType="Int")]
		public System.Nullable<int> NpiReadingId
		{
			get
			{
				return this._NpiReadingId;
			}
			set
			{
				if ((this._NpiReadingId != value))
				{
					this.OnNpiReadingIdChanging(value);
					this.SendPropertyChanging();
					this._NpiReadingId = value;
					this.SendPropertyChanged("NpiReadingId");
					this.OnNpiReadingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NpiWritingId", DbType="Int")]
		public System.Nullable<int> NpiWritingId
		{
			get
			{
				return this._NpiWritingId;
			}
			set
			{
				if ((this._NpiWritingId != value))
				{
					this.OnNpiWritingIdChanging(value);
					this.SendPropertyChanging();
					this._NpiWritingId = value;
					this.SendPropertyChanged("NpiWritingId");
					this.OnNpiWritingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NpiMathId", DbType="Int")]
		public System.Nullable<int> NpiMathId
		{
			get
			{
				return this._NpiMathId;
			}
			set
			{
				if ((this._NpiMathId != value))
				{
					this.OnNpiMathIdChanging(value);
					this.SendPropertyChanging();
					this._NpiMathId = value;
					this.SendPropertyChanged("NpiMathId");
					this.OnNpiMathIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NpiReadingMeanCalculation", DbType="SmallInt")]
		public System.Nullable<short> NpiReadingMeanCalculation
		{
			get
			{
				return this._NpiReadingMeanCalculation;
			}
			set
			{
				if ((this._NpiReadingMeanCalculation != value))
				{
					this.OnNpiReadingMeanCalculationChanging(value);
					this.SendPropertyChanging();
					this._NpiReadingMeanCalculation = value;
					this.SendPropertyChanged("NpiReadingMeanCalculation");
					this.OnNpiReadingMeanCalculationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NpiWritingMeanCalculation", DbType="SmallInt")]
		public System.Nullable<short> NpiWritingMeanCalculation
		{
			get
			{
				return this._NpiWritingMeanCalculation;
			}
			set
			{
				if ((this._NpiWritingMeanCalculation != value))
				{
					this.OnNpiWritingMeanCalculationChanging(value);
					this.SendPropertyChanging();
					this._NpiWritingMeanCalculation = value;
					this.SendPropertyChanged("NpiWritingMeanCalculation");
					this.OnNpiWritingMeanCalculationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NpiMathMeanCalculation", DbType="SmallInt")]
		public System.Nullable<short> NpiMathMeanCalculation
		{
			get
			{
				return this._NpiMathMeanCalculation;
			}
			set
			{
				if ((this._NpiMathMeanCalculation != value))
				{
					this.OnNpiMathMeanCalculationChanging(value);
					this.SendPropertyChanging();
					this._NpiMathMeanCalculation = value;
					this.SendPropertyChanged("NpiMathMeanCalculation");
					this.OnNpiMathMeanCalculationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasScholarshipInfo", DbType="Bit NOT NULL")]
		public bool HasScholarshipInfo
		{
			get
			{
				return this._HasScholarshipInfo;
			}
			set
			{
				if ((this._HasScholarshipInfo != value))
				{
					this.OnHasScholarshipInfoChanging(value);
					this.SendPropertyChanging();
					this._HasScholarshipInfo = value;
					this.SendPropertyChanged("HasScholarshipInfo");
					this.OnHasScholarshipInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsGroupSchools", DbType="Bit NOT NULL")]
		public bool IsGroupSchools
		{
			get
			{
				return this._IsGroupSchools;
			}
			set
			{
				if ((this._IsGroupSchools != value))
				{
					this.OnIsGroupSchoolsChanging(value);
					this.SendPropertyChanging();
					this._IsGroupSchools = value;
					this.SendPropertyChanged("IsGroupSchools");
					this.OnIsGroupSchoolsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishedBy", DbType="VarChar(60)")]
		public string PublishedBy
		{
			get
			{
				return this._PublishedBy;
			}
			set
			{
				if ((this._PublishedBy != value))
				{
					this.OnPublishedByChanging(value);
					this.SendPropertyChanging();
					this._PublishedBy = value;
					this.SendPropertyChanged("PublishedBy");
					this.OnPublishedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalUse", DbType="Bit")]
		public System.Nullable<bool> InternalUse
		{
			get
			{
				return this._InternalUse;
			}
			set
			{
				if ((this._InternalUse != value))
				{
					this.OnInternalUseChanging(value);
					this.SendPropertyChanging();
					this._InternalUse = value;
					this.SendPropertyChanged("InternalUse");
					this.OnInternalUseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hidden", DbType="Bit NOT NULL")]
		public bool Hidden
		{
			get
			{
				return this._Hidden;
			}
			set
			{
				if ((this._Hidden != value))
				{
					this.OnHiddenChanging(value);
					this.SendPropertyChanging();
					this._Hidden = value;
					this.SendPropertyChanged("Hidden");
					this.OnHiddenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentLanguagePrefs")]
	public partial class StudentLanguagePref : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _StudentId;
		
		private string _Language;
		
		private System.DateTime _ModifiedOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStudentIdChanging(int value);
    partial void OnStudentIdChanged();
    partial void OnLanguageChanging(string value);
    partial void OnLanguageChanged();
    partial void OnModifiedOnChanging(System.DateTime value);
    partial void OnModifiedOnChanged();
    #endregion
		
		public StudentLanguagePref()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentId", DbType="Int NOT NULL")]
		public int StudentId
		{
			get
			{
				return this._StudentId;
			}
			set
			{
				if ((this._StudentId != value))
				{
					this.OnStudentIdChanging(value);
					this.SendPropertyChanging();
					this._StudentId = value;
					this.SendPropertyChanged("StudentId");
					this.OnStudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this.OnLanguageChanging(value);
					this.SendPropertyChanging();
					this._Language = value;
					this.SendPropertyChanged("Language");
					this.OnLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedOn", DbType="DateTime NOT NULL")]
		public System.DateTime ModifiedOn
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this.OnModifiedOnChanging(value);
					this.SendPropertyChanging();
					this._ModifiedOn = value;
					this.SendPropertyChanged("ModifiedOn");
					this.OnModifiedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
